spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jnxaread?serverTimezone=Asia/Shanghai
    username:
    password:
  mail:
    host:
    username:
    password:
    nickname: 谨下网
    protocol: smtps
    port: 465
    default-encoding: utf-8
  profiles:
    include: userGrade,userLevel

mybatis:
  #配置Mapper.xml文件位置
  mapper-locations: classpath:mapper/*Mapper.xml,mapper/wrap/*MapperWrap.xml