spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: @spring.datasource.url@
    username: @spring.datasource.username@
    password: @spring.datasource.password@
  mail:
    host: @spring.mail.host@
    username: @spring.mail.username@
    password: @spring.mail.password@
    nickname: 谨下网
    protocol: smtps
    port: @spring.mail.port@
    default-encoding: utf-8
  profiles:
    include: userGrade,userLevel

mybatis:
  #配置Mapper.xml文件位置
  mapper-locations: classpath:mapper/*Mapper.xml,mapper/wrap/*MapperWrap.xml

jnxaread:
  environment:
    current: @jnxaread.environment.current@