spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jnxaread?serverTimezone=Asia/Shanghai
    username: root
#    password: 123
    password: UXCK$$%%9278[l
  mail:
    host: smtp.sina.com
    username: inhive@sina.com
    password: e864188480e4c5b0
    nickname: 谨下网
    protocol: smtps
    port: 465
    default-encoding: utf-8
  profiles:
    include: userGrade,userLevel

mybatis:
  #配置Mapper.xml文件位置
  mapper-locations: classpath:mapper/*Mapper.xml,mapper/wrap/*MapperWrap.xml